index:
    path: /inicio
    controller: App\Controller\HomeController::index

animales:
    path: /animales/{nombre}/{apellidos}
    controller: App\Controller\HomeController::animales
    defaults: {nombre: 'Cosme', apellidos: 'Fulanito'}
    methods: [GET]
    requirements:
        nombre: '[a-zA-Z]+'
        apellidos: '[0-9]+'

redirigir:
    path: /redirigir
    controller: App/Controller/HomeController::redirigir

animalIndex:
    path: /animal/inicio
    controller: App\Controller\AnimalController::index

animalSave:
    path: /animal/save
    controller: App\Controller\AnimalController::save
    methods: [POST]

animalDetail:
    path: /animal/show/{id}
    controller: App\Controller\AnimalController::oneAnimal

animalUpdate:
    path: /animal/update/{id}
    controller: App\Controller\AnimalController::updateAnimal    

animalDelete:
    path: /animal/delete/{id}
    controller: App\Controller\AnimalController::deleteAnimal

crearAnimal:
    path: /animal/create
    controller: App\Controller\AnimalController::createAnimal